// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/glimpse-landing/BookDemo.tsx": () => import("../components/mockups/glimpse-landing/BookDemo.tsx"),
  "./components/mockups/glimpse-landing/Gallery.tsx": () => import("../components/mockups/glimpse-landing/Gallery.tsx"),
  "./components/mockups/glimpse-landing/HowItWorks.tsx": () => import("../components/mockups/glimpse-landing/HowItWorks.tsx"),
  "./components/mockups/glimpse-landing/Landing.tsx": () => import("../components/mockups/glimpse-landing/Landing.tsx"),
  "./components/mockups/glimpse-landing/Pricing.tsx": () => import("../components/mockups/glimpse-landing/Pricing.tsx")
};
